### ISSUE TITLE
___cxa_demangle ld: symbol(s) not found  

### ISSUE THREAD

**Issue by manajay** [Zuikyo/ZIKRouter#10]
Undefined symbols for architecture arm64:
  "___cxa_demangle", referenced from:
      -[NSString(Demangle) demangledAsCPP] in libZIKRouter.a(NSString+Demangle.o)
  "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__init(char const*, unsigned long)", referenced from:
      _demangleSymbolAsString(char const*, unsigned long, DemangleOptions const&) in libZIKRouter.a(NSString+Demangle.o)
  "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_string()", referenced from:
      -[NSString(Demangle) demangledAsSwift] in libZIKRouter.a(NSString+Demangle.o)
      -[NSString(Demangle) demangledAsSimplifiedSwift] in libZIKRouter.a(NSString+Demangle.o)
  "___gxx_personality_v0", referenced from:
      +[ZIKImageSymbol enumerateImages:] in libZIKRouter.a(ZIKImageSymbol.o)
      +[ZIKImageSymbol findSymbolInImage:name:] in libZIKRouter.a(ZIKImageSymbol.o)
      +[ZIKImageSymbol findSymbolInImage:matching:] in libZIKRouter.a(ZIKImageSymbol.o)
      -[NSString(Demangle) demangledAsSwift] in libZIKRouter.a(NSString+Demangle.o)
      _demangleSymbolAsString(char const*, unsigned long, DemangleOptions const&) in libZIKRouter.a(NSString+Demangle.o)
      -[NSString(Demangle) demangledAsSimplifiedSwift] in libZIKRouter.a(NSString+Demangle.o)
      -[NSString(Demangle) demangledAsCPP] in libZIKRouter.a(NSString+Demangle.o)
      ...
ld: symbol(s) not found for architecture arm64

**Comment by Zuikyo** [comment]
Try `ZIKRouter.framework` instead of `libZIKRouter.a`.I didn't meet this error with `ZIKRouter.framework`.

Did this error only exists when using `libZIKRouter.a`?

**Comment by manajay** [comment]
that's a error when i remove wechatOpenSDK dependency. Maybe it's related to Config '-l"c++"' 
That's the difference i found

**Comment by Zuikyo** [comment]
`-demangledAsCPP` is never used. I will publish a new version to remove it.

**Comment by Zuikyo** [comment]
`libZIKRouter.a` need to link `libc++.tbd`. I miss to add it as dependency.

**Comment by manajay** [comment]
👍 优秀
