### ISSUE TITLE
zix_checkMemoryLeak 在线程 com.zuik.router.object_leak_check_queue 中的逻辑导致卡顿/崩溃

### ISSUE THREAD

**Issue by JanXu-Dev** [Zuikyo/ZIKRouter#12]
在 DEBUG 模式下 , zix_checkMemoryLeak 在线程 com.zuik.router.object_leak_check_queue 中触发 - (NSString *)description 方法, 在该方法中, 如果调用了一些 UI 上的行为, 导致卡顿, 如图: 
![bug1](https://user-images.githubusercontent.com/7987282/56454373-44a3e200-6382-11e9-95df-76be72967473.png)
![bug4](https://user-images.githubusercontent.com/7987282/56454468-710c2e00-6383-11e9-99ba-760ae41ef5ba.png)
![bug2](https://user-images.githubusercontent.com/7987282/56454374-45d50f00-6382-11e9-955e-c2c0b291da21.png)
![bug3](https://user-images.githubusercontent.com/7987282/56454376-479ed280-6382-11e9-9ad5-6cd1da2332f3.png)
分别调用 UITableView 和 UIScrollView 的一些必须在 主线程 中操作的属性.
问题: 
1. 是否可以关闭zix_checkMemoryLeak, 影响如何?
2. 是否可以在不关闭的前提下, 有其他解决方案? 暂时是在这几处加上了主线程调用, 但是因为也是第三方库, 希望尽量不修改到其代码.

**Comment by Zuikyo** [comment]
You can use  `ZIKViewRouter.detectMemoryLeakDelay = -1` to disable  memory leak checking.

**Comment by Zuikyo** [comment]
Disable memory leak checking won't affect anything. It's just a little feature to help you check memory leak of view controller.
Thanks for your feedback, I will move checking code to main queue in the next version.

**Comment by JanXu-Dev** [comment]
哈哈, 谢谢~ 期待下个版本
