### ISSUE TITLE
URL Route 必须在 ZIKViewRouter 子类里注册吗

### ISSUE THREAD

**Issue by Frank-728** [Zuikyo/ZIKRouter#16]
有一些不需要参数的页面，都必须创建 ZIKViewRouter 的子类 才能实现 URL Route ?

**Comment by Zuikyo** [comment]
不想用子类的话，可以用 ZIKViewRoute 和 ZIKServiceRoute 对象，demo 里有类似的代码：

```swift
ZIKViewRoute<EditorViewController, ViewRouteConfig>
    .make(withDestination: EditorViewController.self,
          makeDestination: { (config, router) -> EditorViewController? in
            return EditorViewController()
    })
    .register(RoutableView<EditorViewInput>())
    .registerURLPattern(@"router://editor")
```

```objectivec
[ZIKViewRoute<EditorViewController *, ZIKViewRouteConfig *> 
	makeRouteWithDestination:[EditorViewController class] 
	makeDestination:^ EditorViewController * _Nullable(ZIKViewRouteConfig * _Nonnull config, __kindof ZIKRouter<EditorViewController *,ZIKViewRouteConfig *,ZIKViewRemoveConfiguration *> * _Nonnull router) {
        return [[EditorViewController alloc] init];
    }]
    .registerDestinationProtocol(ZIKRoutable(EditorViewInput))
    .registerURLPattern(@"router://editor");
```

如果只需要用 protocol 管理，不需要用 URL，也可以直接注册 protocol：

```swift
ZIKAnyViewRouter.register(RoutableView<EditorViewInput>(), forMakingView: EditorViewController.self)
```
```objectivec
[ZIKViewRouter registerViewProtocol:ZIKRoutable(EditorViewInput) forMakingView:[EditorViewController class]];
```

**Comment by Frank-728** [comment]
ok，明白了，谢谢

**Comment by dengchaojie** [comment]
> 不想用子类的话，可以用 ZIKViewRoute 和 ZIKServiceRoute 对象，demo 里有类似的代码：
> 
> ```swift
> ZIKViewRoute<EditorViewController, ViewRouteConfig>
>     .make(withDestination: EditorViewController.self,
>           makeDestination: { (config, router) -> EditorViewController? in
>             return EditorViewController()
>     })
>     .register(RoutableView<EditorViewInput>())
>     .registerURLPattern(@"router://editor")
> ```
> 
> ```objc
> [ZIKViewRoute<EditorViewController *, ZIKViewRouteConfig *> 
> 	makeRouteWithDestination:[EditorViewController class] 
> 	makeDestination:^ EditorViewController * _Nullable(ZIKViewRouteConfig * _Nonnull config, __kindof ZIKRouter<EditorViewController *,ZIKViewRouteConfig *,ZIKViewRemoveConfiguration *> * _Nonnull router) {
>         return [[EditorViewController alloc] init];
>     }]
>     .registerDestinationProtocol(ZIKRoutable(EditorViewInput))
>     .registerURLPattern(@"router://editor");
> ```
> 
> 如果只需要用 protocol 管理，不需要用 URL，也可以直接注册 protocol：
> 
> ```swift
> ZIKAnyViewRouter.register(RoutableView<EditorViewInput>(), forMakingView: EditorViewController.self)
> ```
> 
> ```objc
> [ZIKViewRouter registerViewProtocol:ZIKRoutable(EditorViewInput) forMakingView:[EditorViewController class]];
> ```
ZIKAnyViewRouter.register(RoutableView<EditorViewInput>(), forMakingView: EditorViewController.self)
请问，这一行代码写到什么位置啊？
