### ISSUE TITLE
pod完成，编译报错了，请协助解决

### ISSUE THREAD

**Issue by dengchaojie** [Zuikyo/ZIKRouter#18]
请参阅[ZIKRouter初学者入门实践Demo](https://github.com/dengchaojie/DemoForZIKRouter.git)

在swift工程，pod 'ZRouter/ServiceRouter', '>= 1.1.0'完成，编译报错。
<img width="594" alt="image" src="https://user-images.githubusercontent.com/13744851/63746281-09d52c00-c8d7-11e9-9d60-7c98a78d6d56.png">

**Comment by Zuikyo** [comment]
1.1.0 的 ServiceRouter 用到了 ViewRouter 里的函数，忘了加上编译宏了。
可以先使用 pod 'ZRouter', '>= 1.1.0'，或者 pod 'ZRouter/ServiceRouter', '1.0.9'
我之后修复一下这个问题。

**Comment by dengchaojie** [comment]
都试过了，不行的，还是同样的错误。

**Comment by Zuikyo** [comment]
这两个我都试过了，编译正常。说明你的 pod 没有成功，或者 clean 一下试试。

**Comment by dengchaojie** [comment]
target 'delete' do
  use_frameworks!
  pod 'ZRouter/ServiceRouter', '1.0.9'
end
<img width="232" alt="image" src="https://user-images.githubusercontent.com/13744851/63749551-45bfbf80-c8de-11e9-9b1d-93aefb1b1954.png">
下载的ZIKRouter还是1.1.0。编译还是报错。

**Comment by Zuikyo** [comment]
看看 pod 后的代码里有没有 ZIKViewRouter。
没有的话试试这个：
pod 'ZIKRouter/ViewRouter', '>= 1.1.0'
pod 'ZRouter/ViewRouter', '>= 1.1.0'

**Comment by dengchaojie** [comment]
pod 'ZIKRouter/ViewRouter', '>= 1.1.0'
  pod 'ZRouter', '>= 1.1.0'
  pod 'ZRouter/ViewRouter', '>= 1.1.0'
文件下都有ViewRouter，还是不行的。

**Comment by Zuikyo** [comment]
那就应该没问题，如果还是同一个编译错误，就 clean 试试。可以用一个空工程测试一下。

**Comment by dengchaojie** [comment]
pod 'ZIKRouter', '1.0.12'
pod 'ZRouter', '1.0.12'
这样写可以。原因可能用ZIKRouter的1.1.0版本有问题。
