### ISSUE TITLE
'init()' is unavailable: Protocol is not declared as routable

### ISSUE THREAD

**Issue by dengchaojie** [Zuikyo/ZIKRouter#19]
请参阅[ZIKRouter初学者入门实践Demo](https://github.com/dengchaojie/DemoForZIKRouter.git)
<img width="481" alt="image" src="https://user-images.githubusercontent.com/13744851/63754667-d8189100-c8e7-11e9-99ce-c2bf12c38116.png">
你的中文文档中，没有EditorDelegate的定义，请问怎么定义？

**Comment by dengchaojie** [comment]
<img width="1094" alt="image" src="https://user-images.githubusercontent.com/13744851/63755376-1d898e00-c8e9-11e9-8bfc-b68ff688ae75.png">
请把这点在详细写一下，有助于普及啊。刚开始看就遇到这个障碍了😀

**Comment by Zuikyo** [comment]
文档里的代码只是演示用法，不是完整的。这里的 EditorDelegate 可以随便写个空的。
建议打开 Router.xcworkspace，看 demo 里的代码，比如 SwiftSampleViewRouter.swift

**Comment by dengchaojie** [comment]
看了。看你定义了一个纯的swift协议PureSwiftSampleViewInput，并在SwiftSampleViewRouter里        register(RoutableView<PureSwiftSampleViewInput>())。为啥我这儿有上面的编译错误呢？

<img width="373" alt="image" src="https://user-images.githubusercontent.com/13744851/63757260-55460500-c8ec-11e9-84e3-59c2ae0d2d91.png">

**Comment by Zuikyo** [comment]
还需要对 protocol 进行声明。参考文档中的 [声明 routable 类型](https://github.com/Zuikyo/ZIKRouter/blob/master/Documentation/Chinese/README.md#2-声明-routable-类型)

```swift
//Declare SwiftSampleViewController is routable
extension SwiftSampleViewController: ZIKRoutableView {
}

//Declare PureSwiftSampleViewInput is routable
extension RoutableView where Protocol == PureSwiftSampleViewInput {
    init() { self.init(declaredProtocol: Protocol.self) }
}
```

**Comment by dengchaojie** [comment]
viewRouter和serviceRouter基本的，能用了。遇到下面的问题，请问怎么解决？
<img width="1002" alt="image" src="https://user-images.githubusercontent.com/13744851/63843268-b0ddc480-c9b8-11e9-9a8a-fb070b1dc3cf.png">

**Comment by Zuikyo** [comment]
指定 protocol 为 class 类型，否则编译器会认为是值类型。

```swift
protocol SecondViewProtocol: class {

}
```

**Comment by dengchaojie** [comment]
<img width="1069" alt="image" src="https://user-images.githubusercontent.com/13744851/63845339-6d855500-c9bc-11e9-8c6f-5c05c30a83a0.png">
reason: '+[delete.SecondVCRouter registerURLPattern:]: unrecognized selector sent to class 0x104367098'

urlRouter崩溃了，请问怎么解决？

**Comment by Zuikyo** [comment]
什么版本？好像 1.0.12 版本的 URLRouter 的 podspec 配置里少了文件，用 1.1.0 吧。

**Comment by dengchaojie** [comment]
嗯嗯，1.1.0可以的。

**Comment by dengchaojie** [comment]
在用快速注册时，有以下崩溃信息，怎么解决？
❌Found router implementation errors: 

❌Declared view protocol (FiveViewProtocol) is not registered with any router.

下面是调用：
```
ZIKAnyViewRouter.register(RoutableView<FiveViewProtocol>(), forMakingView: FiveVC.self)
protocol FiveViewProtocol {
    
}

class FiveVC: UIViewController, FiveViewProtocol {
    
    override func viewDidLoad() {
        
    }
    
}

extension FiveVC: ZIKRoutableView {

}

extension RoutableView where Protocol == FiveViewProtocol {
    init() { self.init(declaredProtocol: Protocol.self) }
}
```

**Comment by dengchaojie** [comment]
在做adapter时，有崩溃：Adapter (SixViewRequiredProtocol) is already registered with a router (SixViewRouter)

下面是调用。我这边试了，如果注销register(adapter: RoutableView<SixViewRequiredProtocol>(), forAdaptee: RoutableView<SixViewProtocol>())可以运行。请作者解释一下哈？

class SixViewAdapter: ZIKViewRouteAdapter {
    
    override class func registerRoutableDestination() {
        //如果可以获取到 router 类，可以直接为 router 添加 RequiredEditorViewInput
        SixViewRouter.register(RoutableView<SixViewRequiredProtocol>())
        
        //如果不能得到对应模块的 router，可以注册 adapter
        register(adapter: RoutableView<SixViewRequiredProtocol>(), forAdaptee: RoutableView<SixViewProtocol>())
    }
    
}

**Comment by Zuikyo** [comment]
这些是 DEBUG 断言，不是崩溃，用来检查你的实现是否正确。
建议先看一遍 README.md 文档。

> ❌Found router implementation errors:
 ❌Declared view protocol (FiveViewProtocol) is not registered with any router.
 extension RoutableView where Protocol == FiveViewProtocol {
     init() { self.init(declaredProtocol: Protocol.self) }
}

这是因为你声明了 FiveViewProtocol 是可路由的，就必须要把这个 protocol 注册给某一个 router。否则使用者使用这个 protocol 时就会得到空的 router。


> Adapter (SixViewRequiredProtocol) is already registered with a router (SixViewRouter)

同一个 protocol 不能同时注册给多个 router，是一对一的。
如果要用 adapter 模式，应该复制一份 SixViewRequiredProtocol，用另一个 RequiredSixViewRequiredProtocol。建议看看 [ModuleAdapter](https://github.com/Zuikyo/ZIKRouter/blob/master/Documentation/Chinese/ModuleAdapter.md)。

**Comment by dengchaojie** [comment]
当调用module时，有下面的提示，请问怎么解决？
<img width="921" alt="image" src="https://user-images.githubusercontent.com/13744851/63908935-88ef6f00-ca53-11e9-9db3-9fca4638eae7.png">
<img width="1027" alt="image" src="https://user-images.githubusercontent.com/13744851/63909021-dff54400-ca53-11e9-83ff-fbca7caf700b.png">

**Comment by dengchaojie** [comment]
> 这些是 DEBUG 断言，不是崩溃，用来检查你的实现是否正确。
> 建议先看一遍 README.md 文档。
> 
> > ❌Found router implementation errors:
> > ❌Declared view protocol (FiveViewProtocol) is not registered with any router.
> > extension RoutableView where Protocol == FiveViewProtocol {
> > init() { self.init(declaredProtocol: Protocol.self) }
> > }
> 
> 这是因为你声明了 FiveViewProtocol 是可路由的，就必须要把这个 protocol 注册给某一个 router。否则使用者使用这个 protocol 时就会得到空的 router。

您好，我问的是，我调用的是快速注册，运行时，有上面的断言？我这边没有发现哪里有问题，请指导一下？
ZIKAnyViewRouter.register(RoutableView(FiveViewProtocol), forMakingView: FiveVC.self)

**Comment by dengchaojie** [comment]
> 在做adapter时，有崩溃：Adapter (SixViewRequiredProtocol) is already registered with a router (SixViewRouter)
> 
> 下面是调用。我这边试了，如果注销register(adapter: RoutableView(), forAdaptee: RoutableView())可以运行。请作者解释一下哈？
> 
> class SixViewAdapter: ZIKViewRouteAdapter {
> 
> ```
> override class func registerRoutableDestination() {
>     //如果可以获取到 router 类，可以直接为 router 添加 RequiredEditorViewInput
>     SixViewRouter.register(RoutableView<SixViewRequiredProtocol>())
>     
>     //如果不能得到对应模块的 router，可以注册 adapter
>     register(adapter: RoutableView<SixViewRequiredProtocol>(), forAdaptee: RoutableView<SixViewProtocol>())
> }
> ```
> 
> }


> > Adapter (SixViewRequiredProtocol) is already registered with a router (SixViewRouter)
> 
> 同一个 protocol 不能同时注册给多个 router，是一对一的。
> 如果要用 adapter 模式，应该复制一份 SixViewRequiredProtocol，用另一个 RequiredSixViewRequiredProtocol。建议看看 [ModuleAdapter](https://github.com/Zuikyo/ZIKRouter/blob/master/Documentation/Chinese/ModuleAdapter.md)。

您好，我问adapter的时候，已经调通了。只是有个小疑问，是不是不能同时启用下面的2行代码啊？
SixViewRouter.register(RoutableView<SixViewRequiredProtocol>())
register(adapter: RoutableView<SixViewRequiredProtocol>(), forAdaptee: RoutableView<SixViewProtocol>())

**Comment by Zuikyo** [comment]
打断点检查一下你的注册代码有没有调用，需要放到某个 adapter 的 registerRoutableDestination 里。有可能在自动注册完毕前你还没有调用注册：

```swift
class SomeAdapter: ZIKViewRouteAdapter {
    override class func registerRoutableDestination() {
        ZIKAnyViewRouter.register(RoutableView<FiveViewProtocol>(), forMakingView: FiveVC.self)
    }
}
```

> SixViewRouter.register(RoutableView<SixViewRequiredProtocol>())
    register(adapter: RoutableView<SixViewRequiredProtocol>(), forAdaptee: RoutableView<SixViewProtocol>())

不能同时调用这两句，只用其中的一种就行。

**Comment by dengchaojie** [comment]
> 打断点检查一下你的注册代码有没有调用，需要放到某个 adapter 的 registerRoutableDestination 里。有可能在自动注册完毕前你还没有调用注册：
> 
> ```swift
> class SomeAdapter: ZIKViewRouteAdapter {
>     override class func registerRoutableDestination() {
>         ZIKAnyViewRouter.register(RoutableView<FiveViewProtocol>(), forMakingView: FiveVC.self)
>     }
> }
> ```
> 
> > SixViewRouter.register(RoutableView())
> > register(adapter: RoutableView(), forAdaptee: RoutableView())
> 
> 不能同时调用这两句，只用其中的一种就行。

当然。但是你的文档上上，这2行都是开启的，没有注销其中一行。对初学者，很容易载坑。

**Comment by Zuikyo** [comment]
嗯，这里的文档需要优化一下。

**Comment by dengchaojie** [comment]
> 嗯，这里的文档需要优化一下。
还有上面的快速注册，没有调通；和module有个问题，请指导一下。后面我们把我的初学者入门实践demo发出来，给其他初学者参考。请参阅[ZIKRouter初学者入门实践Demo](https://github.com/dengchaojie/DemoForZIKRouter.git)😀

**Comment by Zuikyo** [comment]
```swift
Router.perform(
        to: RoutableViewModule<LoginModuleInput>(),
        path: .presentModally(from: self),
        configuring: { (config, _) in
            config.prepareDestination = { destination in
                destination.message = "请登录查看笔记详情" // 这里有错误
            }
        }
    )
```
用 RoutableViewModule 的话，就不能直接指定 destination 的类型了，把`destination.message = "请登录查看笔记详情"`这一行去掉。

```swift
Router.perform(
        to: RoutableViewModule<LoginModuleInput>(),
        path: .presentModally(from: self),
        configuring: { (config, prepareModule) in
            prepareModule({ module in
                
            })
        }
    )
```

> 还有上面的快速注册，没有调通

这个我说了，你的注册代码需要放到某个 adapter 的 registerRoutableDestination 里。有可能在自动注册完毕前你还没有调用注册：

```swift
class SomeAdapter: ZIKViewRouteAdapter {
    override class func registerRoutableDestination() {
        ZIKAnyViewRouter.register(RoutableView<FiveViewProtocol>(), forMakingView: FiveVC.self)
    }
}
```

**Comment by dengchaojie** [comment]
LoginModuleInput定义了一个var message: String? { get set }。编译时被要求重写get和set。在下面给message做了赋值，但是不知道在哪里去用这个message，请指导一下？
```
// module+RoutableViewModule
        Router.perform(
            to: RoutableViewModule<LoginModuleInput>(),
            path: .presentModally(from: self),
            configuring: { (config, prepareModule) in
                
                prepareModule({ module in
                    module.message = "hello, this is LoginModuleInput"
                })
                
        }
        )

extension ViewMakeableConfiguration: LoginModuleInput where Destination == LoginViewProtocol, Constructor == (String) -> LoginViewProtocol? {
    var message: String? {
        get {
            return self.constructorContainer["message"] as? String
        }
        set {
            self.constructorContainer["message"] = newValue
        }
    }
}
```
[ZIKRouter初学者入门实践Demo](https://github.com/dengchaojie/DemoForZIKRouter.git)

**Comment by Zuikyo** [comment]
看 [自定义 configuration 传参](https://github.com/Zuikyo/ZIKRouter/blob/master/Documentation/Chinese/CustomConfiguration.md) 文档。

建议在 LoginModuleInput 上用工厂方法传递参数，而不是用属性：

```swift
protocol LoginModuleInput {
    var makeDestinationWith: (_ message: String) -> LoginViewProtocol? { get }
}
```

```swift
extension ViewMakeableConfiguration: LoginModuleInput where Destination == LoginViewProtocol, Constructor == (String) -> LoginViewProtocol? {
}

class LoginViewRouter: ZIKViewRouter< LoginViewController, ViewRouteConfig> {
    
    override class func registerRoutableDestination() {
        registerExclusiveView(LoginViewController.self)
        register(RoutableViewModule<LoginModuleInput>())
    }
    
    // 使用自定义 configuration
    override class func defaultRouteConfiguration() -> ViewRouteConfig {
        let config = ViewMakeableConfiguration<LoginViewProtocol, (String) -> LoginViewProtocol?>({ _ in return nil })	    
    
	// 工厂方法，使用者调用 makeDestinationWith 向模块传参
	config.makeDestinationWith = { [unowned config] (message) in
        
            // makeDestination 会被用于创建 destination
            // 用闭包捕获了传入的参数，可以直接用于创建 destination
            config.makeDestination = { () in
	         // 调用自定义初始化方法，把 message 传给 view
	         let destination = LoginViewController(message: message)            
	         return destination
	     }
        
             if let destination = config.makeDestination?() {
                 // 设置 makedDestination 后，router 在执行时就会直接使用此对象
                 config.makedDestination = destination
                 return destination
             }
             return nil
	 }
	 return config
    }
    
    override func destination(with configuration: ZIKViewMakeableConfiguration<LoginViewController>) -> LoginViewController? {
        // 注意这里类型转换不要出错
        if let config = configuration as? ViewMakeableConfiguration<LoginViewProtocol, (String) -> LoginViewProtocol?>,
            let makeDestination = config.makeDestination {
            return makeDestination() as? LoginViewController ?? nil
        }
        return nil
    }
    
}
```
