### ISSUE TITLE
获取模块makeDestination 当destination是view而不是controller时崩溃

### ISSUE THREAD

**Issue by KelyCocoa** [Zuikyo/ZIKRouter#2]
你好 我用makeDestination 获取子模块view时崩溃 检查源码是- (void)_performGetDestination:(id)destination fromSource:(nullable id)source函数中self.stateBeforeRoute = [destination zix_presentationState];造成的，因为zix_presentationState成controller分类中的扩展方法。然而我们在获取模块的时候这个模块可能是controller 也可能是view 不应该只是controller，希望您能给出解决方案，最后我想说的是 我爱死你这套路由方案了！！！

**Comment by Zuikyo** [comment]
多谢反馈~看了一下，这个问题应该已经修复了，之前的 0.几的版本是测试版，请使用 1.0.0 正式版本试试。

Thanks for feedback. This bug is fixed in 1.0.0 release.

**Comment by KelyCocoa** [comment]
非常感谢您的回复， 请问1.0.0是最近更新的，我上周用pod加载的代码，我觉得应该是最新的了，您是否已经更新仓库

**Comment by Zuikyo** [comment]
1.0.0是上周刚发布的，可能需要先用pod repo update更新一下本地pod
