### ISSUE TITLE
Compiler error on ZRouter under xCode 10.1 swift 4

### ISSUE THREAD

**Issue by lzhlewis2015** [Zuikyo/ZIKRouter#21]
"_ZIKRouteActionPerformRoute", referenced from:
      closure #1 (A) -> () in ZRouter.ViewRouterType.perform(path: ZRouter.ViewRoutePath, completion: (Swift.Bool, A?, __C.ZIKRouteAction, Swift.Error?) -> ()) -> ZRouter.ViewRouter<A, B>? in ViewRouter.o
      closure #1 (A) -> () in ZRouter.ViewRouter.performRoute(completion: (Swift.Bool, A?, __C.ZIKRouteAction, Swift.Error?) -> ()) -> () in ViewRouter.o
      closure #1 (A) -> () in ZRouter.ServiceRouterType.perform(completion: (Swift.Bool, A?, __C.ZIKRouteAction, Swift.Error?) -> ()) -> ZRouter.ServiceRouter<A, B>? in ServiceRouter.o
      closure #1 (A) -> () in ZRouter.ServiceRouter.performRoute(completion: (Swift.Bool, A?, __C.ZIKRouteAction, Swift.Error?) -> ()) -> () in ServiceRouter.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by Zuikyo** [comment]
Do you import the framework with cocoapods ?
I didn't meet your problem, or you can provide a demo.
ZRouter depends on ZIKRouter. You should import both of two frameworks.

**Comment by lzhlewis2015** [comment]
Yes, with cocoapods.
It was resolved by upgraded the cocoapod version first then run pod install again afterwards.
