### ISSUE TITLE
大佬，看看这个问题怎么办

### ISSUE THREAD

**Issue by imphila** [Zuikyo/ZIKRouter#24]
Return expression of type 'UIViewController' does not conform to 'ZIKViewRouteContainer'
<img width="916" alt="WX20200624-173734@2x" src="https://user-images.githubusercontent.com/9293377/85531693-9197de00-b641-11ea-91b2-8d980062c249.png">

**Comment by imphila** [comment]
let url =  "abc://bvc/a?apple=1"
        let b = ZIKViewRouter<UIViewController, ZIKViewRouteConfiguration>.router(forURL: url)
        b?.perform(ZIKViewRoutePath.push(from: self), configuring: { (config) in
            
            config.containerWrapper = { vc in
                vc.modalPresentationStyle = .overFullScreen
                return vc
            }
            
        })

**Comment by Zuikyo** [comment]
Read the documentation of `containerWrapper`. You should wrap the vc in a container (UINavigationController, UITabBarController or UISplitViewController), and return the container.

**Comment by Zuikyo** [comment]
If you only need to change `vc.modalPresentationStyle`, you should do it in `prepareDestination`.

```
let router = ZIKAnyViewRouter.router(forURL: "abc://bvc/a?apple=1")
router?.perform(.push(from: self), configuring: { (config) in
    config.prepareDestination = { [weak self] destination in
        if let destination = destination as? UIViewController {
            destination.modalPresentationStyle = .fullScreen
        }
    }
})
```

**Comment by imphila** [comment]
Get it. Thank you
