### ISSUE TITLE
老铁，创建模板报错

### ISSUE THREAD

**Issue by ma125125t** [Zuikyo/ZIKRouter#27]
The operation couldn’t be completed. (IDEFoundation.IDETemplateParseError error 1.)

**Comment by ma125125t** [comment]
![image.png](https://i.loli.net/2020/08/18/nObCWzfhF19P7TQ.png)

**Comment by FFFang** [comment]
给您的zuikxyo@gmail.com邮箱发送了一封邮件，麻烦查收一下。

**Comment by Zuikyo** [comment]
I tested it in Xcode 12 beta, and there is no error.

**Comment by ma125125t** [comment]
我在Xcode11及Xcode12都测试过，都提示这个错误。
Template路径为~/Library/Developer/Xcode/Templates/
![image](https://user-images.githubusercontent.com/8197207/94116802-0c110d80-fe7e-11ea-9a1a-9027fde5f582.png)
