### ISSUE TITLE
Will ZIKRouter support  OS X app?

### ISSUE THREAD

**Issue by alexlee002** [Zuikyo/ZIKRouter#5]
I plan to use this framework in my Mac & iOS projects, so are you planing to support OS X?

**Comment by Zuikyo** [comment]
It's in the todo list. Supporting multi platform is the next step. But it will take some time.
To support Mac, we need to:

* Use compiling macro and AVAILABLE macro to support different platforms
* Handle classes in different platforms, like `UIViewController` and `NSViewController`, `UIApplication` and `NSApplication`
* Adapt different transition style in ZIKViewRouter  for different platforms, mark ZIKViewRouteType with NS_ENUM_AVAILABLE
* Handle those hooked system methods in ViewController and View
* Add corresponding categories for ViewController and View in different platforms, see `ZIKViewRouter/Extensions` and `ZIKViewRouter/Private`

In a conclusion, we need to modify ZIKViewRouter. ZIKServiceRouter is not associated with iOS classes, so ZIKServiceRouter can support different platforms now.

**Comment by Zuikyo** [comment]
@alexlee002  ZIKRouter supports mac OS 10.10 now. You can try the latest commit.
It may need further test in old mac OS. Please report if there are any problems.

**Comment by alexlee002** [comment]
OK! Great job! Thank you very much!
