### ISSUE TITLE
'ZIKBlockViewRouter.h' file not found 

### ISSUE THREAD

**Issue by JanXu-Dev** [Zuikyo/ZIKRouter#8]
Cocoapods 更新 v1.0.3 好像缺少文件: 'ZIKBlockViewRouter.h' file not found 
![image](https://user-images.githubusercontent.com/7987282/46130910-05d6ff00-c26d-11e8-904b-8d7a1bdd7b4c.png)

**Comment by Zuikyo** [comment]
这几个类都放到`ZIKBlockViewRouter`里了，看看是不是 Xcode 的 bug，clean 一下试试

**Comment by JanXu-Dev** [comment]
clean 过, 用的是 Xcode 10, 然后全文搜索的结果如图 :
![image](https://user-images.githubusercontent.com/7987282/46131306-e42a4780-c26d-11e8-9b00-14c36999e069.png)

**Comment by Zuikyo** [comment]
把`~/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/`缓存删了，`Pods/ZIKRouter`的代码也删了，再重新`pod update`试试。
在 1.0.3 里其他文件都去掉了，就剩下了`ZIKBlockServiceRouter.h``ZIKBlockServiceRouter.m``ZIKBlockViewRouter.h``ZIKBlockViewRouter.m`，所以你的搜索结果是对的。

**Comment by Zuikyo** [comment]
我用一个新项目测试是正常的。

**Comment by JanXu-Dev** [comment]
把 Cocoapods 从项目移除, 然后重新 install 后就 OK 了, 谢谢

**Comment by Zuikyo** [comment]
不客气，有其他建议也可以多多交流
